function:
  image: 'hmctspublic.azurecr.io/ccpay/callback-function:latest'
  environment:
    name: "dummy"
  triggers:
    - type: azure-servicebus
      topicName: "servicecallbacktopic"
      subscriptionName: defaultServiceCallbackSubscription
      connection: SERVICE_CALLBACK_BUS_CONNECTION
      queueLength: 1
  keyVaults:
    ccpay:
      secrets:
        - AppInsightsInstrumentationKey
        - sb-primary-connection-string
servicebus:
  enabled: false
