function:
  # Don't modify below here
  image: ${IMAGE_NAME}
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: 124e39c3-6dad-49ef-aede-d2cddac865c2
    SERVICE_CALLBACK_SUBSCRIPTION: pr-subscription-name
  secrets:
    SB_ACCESS_KEY:
      secretRef: fees-pay-sb-preview
      key: primaryKey
    SB_CONNECTION_STRING:
      secretRef: fees-pay-sb-preview
      key: connectionString
    SERVICE_CALLBACK_BUS_CONNECTION:
      secretRef: servicebus-secret-topic-{{ .Release.Name }}-servicebus-servicecallbacktopic
      key: connectionString
servicebus:
  resourceGroup: fees-pay-rg
  sbNamespace: "fees-pay-servicebus-preview"
  teamName: "Fees Pay"
  location: ukwest
  serviceplan: standard
  setup:
    topics:
      - name: topic
        subscriptionNeeded: yes
  enabled: true
