java:
  secrets:
    STORAGE_ACCOUNT_NAME:
      secretRef: storage-secret-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_ACCOUNT_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_ACCOUNT_SECONDARY_KEY:
      secretRef: storage-secret-{{ .Release.Name }}
      key: accessKey
    STORAGE_CRIME_ACCOUNT_NAME:
      secretRef: storage-secret-crime-{{ .Release.Name }}
      key: storageAccountName
    STORAGE_CRIME_ACCOUNT_KEY:
      secretRef: storage-secret-crime-{{ .Release.Name }}
      key: accessKey
    SB_ACCESS_KEY:
      secretRef: servicebus-secret-namespace-{{ .Release.Name }}-servicebus
      key: primaryKey
    SB_NAMESPACE:
      secretRef: servicebus-secret-namespace-{{ .Release.Name }}-servicebus
      key: namespaceName
  keyVaults:
    reform-scan:
      resourceGroup: reform-scan
      secrets:
        - name: reports-email-username
          alias: SMTP_USERNAME
        - name: reports-email-password
          alias: SMTP_PASSWORD
        - name: reform-reports-recipients
          alias: REPORTS_RECIPIENTS
        - name: reconciliation-api-key
          alias: RECONCILIATION_API_KEY
        - name: reconciliation-report-api-key
          alias: RECONCILIATION_REPORT_API_KEY
        - name: s2s-secret-blob-router
          alias: S2S_SECRET
        - name: reconciliation-report-recipients
          alias: RECONCILIATION_REPORT_RECIPIENTS
  environment:
    DB_HOST: "{{ .Release.Name }}-postgresql"
    DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    DB_USER: "{{ .Values.postgresql.postgresqlUsername}}"
    DB_PASSWORD: "{{ .Values.postgresql.postgresqlPassword}}"
    DB_PORT: '5432'
    DB_CONN_OPTIONS: ""

    DELETE_DISPATCHED_FILES_CRON: "0/10 * * * * *"
    TASK_SCAN_DELAY: "1000" # in millis
    SEND_NOTIFICATIONS_CRON: "0/10 * * * * *"

    FLYWAY_SKIP_MIGRATIONS: false

    STORAGE_BULKSCAN_URL: https://bulkscanaat.blob.core.windows.net
    STORAGE_PCQ_URL: "https://pcqsharedaat.blob.core.windows.net"

    STORAGE_URL: "https://$(STORAGE_ACCOUNT_NAME).blob.core.windows.net"
    STORAGE_CRIME_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=$(STORAGE_CRIME_ACCOUNT_NAME);AccountKey=$(STORAGE_CRIME_ACCOUNT_KEY);EndpointSuffix=core.windows.net"

    PCQ_BACKEND_API_URL: "http://pcq-backend-aat.service.core-compute-aat.internal"

    BULK_SCAN_PROCESSOR_URL: http://bulk-scan-processor-aat.service.core-compute-aat.internal
    CRIME_DESTINATION_CONTAINER: bs-sit-scans-received

    NOTIFICATIONS_QUEUE_ACCESS_KEY_SEND_NAME: "RootManageSharedAccessKey"
    NOTIFICATIONS_QUEUE_NAMESPACE: "$(SB_NAMESPACE)"
    NOTIFICATIONS_QUEUE_SEND_ACCESS_KEY: "$(SB_ACCESS_KEY)"

    S2S_NAME: "reform_scan_blob_router"
    S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  postgresql:
    enabled: true
    postgresqlUsername: db_user
    postgresqlPassword: db_pass
    postgresqlDatabase: db

reformblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bulkscan
      - bulkscan-rejected
      - bulkscanauto
      - bulkscanauto-rejected
      - crime
      - crime-rejected
      - cmc
      - sscs
      - finrem
      - divorce
      - nfd
      - probate
      - publiclaw
      - privatelaw
      - pcq
      - pcq-rejected

crimeblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  releaseNameOverride: crime-{{ .Release.Name }}
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - bs-sit-scans-received

pcqblobstorage:
  enabled: true
  resourceGroup: reform-scan-aks
  releaseNameOverride: pcq-{{ .Release.Name }}
  teamName: "BSP"
  location: ukwest
  setup:
    containers:
      - pcq

servicebus:
  resourceGroup: reform-scan-aks
  teamName: "BSP"
  location: uksouth
  serviceplan: basic
  setup:
    queues:
      - name: notifications
  enabled: true

