java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  disableKeyVaults: true
  environment:
    FAVOURITE_FRUIT: IAC Fees Dev
    RUN_DB_MIGRATION_ON_STARTUP: 'true'
    RUN_DB_REPAIR_ON_STARTUP: 'true'
    FLYWAY_USER: ${FLYWAY_USER}
    FLYWAY_PASSWORD: ${FLYWAY_PASSWORD}
    POSTGRES_HOST: ${POSTGRES_HOST}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

