# config used by staging aat pod
java:
  image: https://hmcts.azurecr.io/hmcts/ccd-data-store-api:latest
  ingressHost: 
  environment:
    DATA_STORE_DB_HOST: ccd-data-store-api-postgres-db-v11-aat.postgres.database.azure.com
