nodejs:
  applicationPort: 3344
  cpuLimits: 500m
  cpuRequests: 100m
  memoryRequests: 256Mi
  memoryLimits: 1024Mi
  image: 'hmctspublic.azurecr.io/fact/public-frontend:latest'
  ingressHost: fact-public-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: fact
  keyVaults:
    fact-kv:
      secrets:
        - name: app-insights-connection-string
          alias: APP_INSIGHTS_CONNECTION_STRING
        - name: session-secret
          alias: SESSION_SECRET
  environment:
    DYNATRACE_JSTAG_KEY: '{{ .Values.global.environment }}'
    SESSION_COOKIE_SAME_SITE: 'lax'
    DATA_API_URL: 'https://fact-data-api.{{ .Values.global.environment }}.platform.hmcts.net'
