java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/pdda-public-display-data-aggregator:latest
  ingressHost: 
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    POSTGRES_USER: "{{ .Values.postgresql.auth.username }}"
    APIM_ENABLED: true
    APIM_URI: https://sds-api-mgmt.staging.platform.hmcts.net/pip/data-management