job:
  image: 'hmctspublic.azurecr.io/am/role-assignment-batch-service:latest'
  ingressHost: am-role-assignment-batch-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4099
  aadIdentityName: am
  kind: CronJob
  global:
    jobKind: CronJob
  keyVaults:
    am:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: am-role-assignment-service-s2s-secret
          alias: AM_ROLE_ASSIGNMENT_SERVICE_SECRET
        - name: role-assignment-service-POSTGRES-PASS
          alias: ROLE_ASSIGNMENT_DB_PASSWORD
        - name: role-assignment-service-POSTGRES-USER
          alias: ROLE_ASSIGNMENT_DB_USERNAME
        - name: role-assignment-service-POSTGRES-HOST
          alias: ROLE_ASSIGNMENT_DB_HOST
        - name: am-sendgrid-api-key
          alias: AM_SENDGRID_API_KEY
        - name: judicial-booking-service-POSTGRES-PASS
          alias: JUDICIAL_BOOKING_SERVICE_POSTGRES_PASS
        - name: judicial-booking-service-POSTGRES-USER
          alias: JUDICIAL_BOOKING_SERVICE_POSTGRES_USER
        - name: judicial-booking-service-POSTGRES-HOST
          alias: JUDICIAL_BOOKING_SERVICE_POSTGRES_HOST
        - name: role-assignment-batch-service-EMAIL-LIST
          alias: EMAIL_LIST
  environment:
    BATCH_ENV: "{{ .Values.global.environment }}"
    EMAIL_ENABLED: false
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    JUDICIAL_BOOKING_SERVICE_POSTGRES_PORT: 5432
    JUDICIAL_BOOKING_SERVICE_POSTGRES_DATABASE: judicial_booking
postgresql:
  enabled: false
