# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/ccpay-refunds-api:latest
  ingressHost: 
  environment:
    BULKSCAN_API_URL: "http://ccpay-bulkscanning-api-aat.service.core-compute-aat.internal"
