# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  environment:
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    APIM_URI: https://sds-api-mgmt.staging.platform.hmcts.net
    MEDIA_KIND_SUBSCRIPTION: pre-mediakind-stg
    PLATFORM_ENV_TAG: Staging
    AZURE_INGEST_SA: preingestsastg
    AZURE_FINAL_SA: prefinalsastg
    MEDIA_SERVICE: MediaKind
    ENABLE_NEW_EMAIL_SERVICE: true
  image: https://hmcts.azurecr.io/hmcts/pre-api:latest
  ingressHost: 
