# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  environment:
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
    APIM_URI: https://sds-api-mgmt.staging.platform.hmcts.net
    MEDIA_KIND_SUBSCRIPTION: pre-mediakind-stg
    PLATFORM_ENV_TAG: Staging
    AZURE_INGEST_SA: preingestsastg
    AZURE_FINAL_SA: prefinalsastg
    MEDIA_SERVICE: MediaKind
    ENABLE_NEW_EMAIL_SERVICE: true
    ENABLE_STREAMING_LOCATOR_ON_START: true
    ENABLE_AUTOMATED_EDITING: true
    ENABLE_ENHANCED_PROCESSING: true
    ENABLE_NULL_DURATION_UPSERT: false
    ENABLE_MIGRATION_ADMIN_ENDPOINTS: true
    ENABLE_MULTI_FFMPEG_COMMAND: false
    ENABLE_MIGRATED_DATA: true
  image: https://hmcts.azurecr.io/hmcts/pre-api:latest
  ingressHost: 
