java:
  applicationPort: 8989
  image: 'hmctspublic.azurecr.io/fact/data-api:latest'
  ingressHost: fact-data-api.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: fact
  keyVaults:
    fact-kv:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: data-api-POSTGRES-DATABASE
          alias: DB_NAME
        - name: data-api-POSTGRES-PASS
          alias: DB_PASSWORD
        - name: data-api-POSTGRES-PORT
          alias: DB_PORT
        - name: data-api-POSTGRES-USER
          alias: DB_USER
        - name: data-api-POSTGRES-HOST
          alias: DB_HOST
        - name: api-app-reg-id
          alias: APP_REG_ID
        - name: bstrap-os-key
          alias: OS_KEY
        - name: bstrap-cath-api-url
          alias: CATH_API_URL
        - name: bstrap-slack-token
          alias: SLACK_TOKEN
        - name: bstrap-slack-channel-id
          alias: SLACK_CHANNEL_ID
  environment:
    RUN_DB_MIGRATION_ON_STARTUP: false
    AZURE_MANAGED_IDENTITY_ENABLED: true
    AZURE_STORAGE_ACCOUNT_NAME: factsa{{ .Values.global.environment }}
    TESTING_SUPPORT_ENABLE_API: false
