# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/darts-gateway:latest
  ingressHost: 
  environment:
    DARTS_API_URL: https://darts-api.staging.platform.hmcts.net
    TESTING_SUPPORT_ENDPOINTS_ENABLED: true
