# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/pip-account-management:latest
  ingressHost: 
  environment:
    ENABLE_TESTING_SUPPORT_API: true
    MANAGED_IDENTITY_CLIENT_ID: 8d0ead51-3b31-44df-a78e-ada4eea9fe87
    MAX_SYSTEM_ADMIN_ACCOUNTS: 20
