nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devcpuRequests: 250m
  devcpuLimits: 2000m
  devmemoryRequests: 512Mi
  devmemoryLimits: 2048Mi
  keyVaults:
    wa:
      secrets:
        - app-insights-connection-string
        - name: cft-task-POSTGRES-USER-FLEXIBLE-REPLICA
          alias: tm-db-user
        - name: cft-task-POSTGRES-PASS-FLEXIBLE-REPLICA
          alias: tm-db-password
        - name: rd-caseworker-ref-api-POSTGRES-USER
          alias: crd-db-user
        - name: rd-caseworker-ref-api-POSTGRES-PASS
          alias: crd-db-password
        - name: rd-location-ref-api-POSTGRES-USER
          alias: lrd-db-user
        - name: rd-location-ref-api-POSTGRES-PASS
          alias: lrd-db-password
  environment:
    AUTH_ENABLED: false
    REDIS_HOST: ${SERVICE_NAME}-redis-master
redis:
  enabled: true
  architecture: standalone
  master:
    persistence:
      enabled: false
  auth:
    enabled: false
