nodejs:
  applicationPort: 3100
  aadIdentityName: wa
  ingressHost: wa-reporting-frontend.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/wa/reporting-frontend:latest'
  cpuRequests: 250m
  cpuLimits: 2000m
  memoryRequests: 512Mi
  memoryLimits: 2048Mi
  keyVaults:
    wa:
      secrets:
        - app-insights-connection-string
        - wa-reporting-redis-host
        - wa-reporting-redis-port
        - wa-reporting-redis-access-key
        - wa-reporting-frontend-client-secret
        # - session-secret
        - name: cft-task-POSTGRES-USER-FLEXIBLE-REPLICA
          alias: tm-db-user
        - name: cft-task-POSTGRES-PASS-FLEXIBLE-REPLICA
          alias: tm-db-password
        - name: rd-caseworker-ref-api-POSTGRES-USER
          alias: crd-db-user
        - name: rd-caseworker-ref-api-POSTGRES-PASS
          alias: crd-db-password
        - name: rd-location-ref-api-POSTGRES-USER
          alias: lrd-db-user
        - name: rd-location-ref-api-POSTGRES-PASS
          alias: lrd-db-password
  environment:
    ALLOW_CONFIG_MUTATIONS: true
    TM_DB_HOST: cft-task-postgres-db-flexible-replica-{{ .Values.global.environment }}.postgres.database.azure.com
    TM_DB_NAME: cft_task_db
    TM_DB_SCHEMA: analytics
    TM_DB_OPTIONS: sslmode=verify-full
    CRD_DB_HOST: rd-caseworker-ref-api-postgres-db-v16-{{ .Values.global.environment }}.postgres.database.azure.com
    CRD_DB_NAME: dbrdcaseworker
    CRD_DB_SCHEMA: rdstaffreport
    CRD_DB_OPTIONS: sslmode=verify-full
    LRD_DB_HOST: rd-location-ref-api-postgres-db-v16-{{ .Values.global.environment }}.postgres.database.azure.com
    LRD_DB_NAME: dbrdlocationref
    LRD_DB_SCHEMA: locrefdata
    LRD_DB_OPTIONS: sslmode=verify-full
    IDAM_PUBLIC_URL: https://hmcts-access.{{ .Values.global.environment }}.platform.hmcts.net
    MANAGE_CASE_BASE_URL: https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net
redis:
  enabled: false
  image:
    registry: hmctspublic.azurecr.io
    repository: imported/bitnami/redis
global:
  security:
    allowInsecureImages: true
