java:
  image: 'hmctspublic.azurecr.io/am/role-assignment-service:latest'
  ingressHost: am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 4096
  aadIdentityName: am
  startupDelay: 30
  startupFailureThreshold: 5
  keyVaults:
    am:
      secrets:
        - am-role-assignment-service-s2s-secret
        - role-assignment-service-POSTGRES-PASS
        - AppInsightsInstrumentationKey
        - role-assignment-service-IDAM-CLIENT-SECRET
        - role-assignment-service-IDAM-ADMIN-SECRET
        - role-assignment-service-LD-SDK-KEY
  environment:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_USER_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    ROLE_ASSIGNMENT_S2S_AUTHORISED_SERVICES: ccd_gw,am_role_assignment_service,am_org_role_mapping_service,wa_task_management_api,wa_task_configuration_api,xui_webapp,aac_manage_case_assignment,ccd_data,wa_workflow_api,wa_task_monitor,wa_case_event_handler,iac,hmc_cft_hearing_service,ccd_case_disposer
    ROLE_ASSIGNMENT_DB_PORT: 5432
    ROLE_ASSIGNMENT_DB_NAME: role_assignment
    ROLE_ASSIGNMENT_DB_HOST: am-role-assignment-service-postgres-db-v11-{{ .Values.global.environment }}.postgres.database.azure.com
    ROLE_ASSIGNMENT_DB_USERNAME: am@am-role-assignment-service-postgres-db-v11-{{ .Values.global.environment }}
    ROLE_ASSIGNMENT_DB_OPTIONS: "?stringtype=unspecified&reWriteBatchedInserts=true&sslmode=require"
    CCD_DATA_STORE_URL: http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    ROLE_ASSIGNMENT_IDAM_CLIENT_ID: am_role_assignment
    MICROSERVICE_NAME: am_role_assignment_service
    PACT_BROKER_FULL_URL: https://pact-broker.platform.hmcts.net
    PACT_BROKER_URL: pact-broker.platform.hmcts.net
    PACT_BROKER_PORT: 443
    PACT_BROKER_SCHEME: https
    ENABLE_FEIGN_HYSTRIX: false
    ROLE_ASSIGNMENT_IDAM_ADMIN_USERID: ras-validation-system@hmcts.net
    APPLICATION_LOGGING_LEVEL: INFO
    BYPASS_ORG_DROOL_RULE: false
    RUN_DB_MIGRATION_ON_STARTUP: false
    RUN_LD_ON_STARTUP: true
