java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/am-role-assignment-service:latest
  ingressHost: 
  keyVaults:
    am:
      secrets:
        - name: am-role-assignment-service-s2s-secret
          alias: AM_ROLE_ASSIGNMENT_SERVICE_SECRET
        - name: role-assignment-service-POSTGRES-PASS-V15
          alias: ROLE_ASSIGNMENT_DB_PASSWORD
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: role-assignment-service-IDAM-CLIENT-SECRET
          alias: ROLE_ASSIGNMENT_IDAM_CLIENT_SECRET
        - name: role-assignment-service-IDAM-ADMIN-SECRET
          alias: ROLE_ASSIGNMENT_IDAM_ADMIN_PASSWORD
        - name: role-assignment-service-LD-SDK-KEY
          alias: LD_SDK_KEY
  environment:
    BYPASS_ORG_DROOL_RULE: true
    ROLE_ASSIGNMENT_DB_HOST: am-role-assignment-service-postgres-db-v15-{{ .Values.global.environment }}.postgres.database.azure.com
    ROLE_ASSIGNMENT_DB_USERNAME: pgadmin
    RUN_DB_MIGRATION_ON_STARTUP: true
