# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/ccpay-service-request-cpo-update-service:latest
  ingressHost: 
