nodejs:
  applicationPort: 3000
idam-pr:
  enabled: false
xui-webapp:
  enabled: false
tags:
  ccd-pr: false
  ccd-idam-pr: false

java:
  applicationPort: 8099
  image: 'hmctspublic.azurecr.io/fis/cos-api:latest'
  ingressHost: fis-cos-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: fis

  environment:
    NODE_ENV: production
    REFORM_TEAM: fis
    REFORM_SERVICE_NAME: fis-cos-api

    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net'
    IDAM_API_BASEURL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net'
    CASE_DATA_STORE_BASEURL: 'http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    CCD_CASE_DOCS_AM_API: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"

  keyVaults:
    fis:
      secrets:
        - name: idam-system-user-name
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-system-user-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: s2s-secret-fis-cos-api
          alias: S2S_SECRET
        - name: AppInsightsInstrumentationKey
