java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    LAU_EUD_DB_NAME: "{{ .Values.postgresql.auth.database }}"
    LAU_EUD_DB_USERNAME: "lauuser"
    LAU_EUD_DB_PASSWORD: "{{ .Values.postgresql.auth.password }}"
    LAU_EUD_DB_ADMIN_USERNAME: "{{ .Values.postgresql.auth.username }}"
    LAU_EUD_DB_ADMIN_PASSWORD: "{{ .Values.postgresql.auth.password }}"
    LAU_EUD_DB_HOST: "{{ .Release.Name }}-postgresql"
    LAU_EUD_DB_PORT: "5432"
    FLYWAY_URL: "jdbc:postgresql://{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database}}"
    FLYWAY_USER: "{{ .Values.postgresql.auth.username }}"
    FLYWAY_PASSWORD: "{{ .Values.postgresql.auth.password }}"
    FLYWAY_NOOP_STRATEGY: "false"
    LAU_EUD_DB_CONN_OPTIONS: "?sslmode=allow"
    DB_ENCRYPTION_ENABLED: "No"
    LAU_FLYWAY_MIGRATE_DB: "true"
    S2S_URL: http://rpe-service-auth-provider-aat.service.core-compute-aat.internal
    IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
    IDAM_CLIENT_NAME: lau
    RD_PROFESSIONAL_API_URL: http://rd-professional-api-aat.service.core-compute-aat.internal
    IDAM_CLIENT_REDIRECT_URL: https://lau-eud-backend-aat.service.core-compute-aat.internal/oauth2/callback
    S2S_MICROSERVICE: lau_eud_backend
  postgresql:
    enabled: true
    primary:
      initdb:
        user: "postgres"
        scripts:
          init.sql: |-
            CREATE ROLE lauuser WITH LOGIN PASSWORD 'javapassword';
            CREATE EXTENSION IF NOT EXISTS pgcrypto;
            CREATE EXTENSION IF NOT EXISTS citext;
