java:
  secrets:
    SB_ACCESS_KEY:
      secretRef: reform-scan-sb-preview
      key: primaryKey
    SB_CONNECTION_STRING:
      secretRef: reform-scan-sb-preview
      key: connectionString
  environment:
    DB_HOST: "{{ .Release.Name }}-postgresql"
    DB_NAME: "{{ .Values.postgresql.auth.database}}"
    DB_USER: "{{ .Values.postgresql.auth.username}}"
    DB_PASSWORD: "{{ .Values.postgresql.auth.password}}"
    DB_PORT: '5432'
    DB_CONN_OPTIONS: ""
    FLYWAY_SKIP_MIGRATIONS: false
    QUEUE_ACCESS_KEY_LISTEN_NAME: "RootManageSharedAccessKey"
    QUEUE_NAME: "{{ .Release.Name }}-servicebus-notifications"
    QUEUE_NAMESPACE: "reform-scan-sb-preview"
    QUEUE_READ_ACCESS_KEY: "$(SB_ACCESS_KEY)"
    S2S_URL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    PENDING_NOTIFICATIONS_TASK_DELAY_IN_MS: 500
    PENDING_NOTIFICATIONS_SEND_DELAY_IN_MINUTE: 0
    SB_NAMESPACE: "reform-scan-sb-preview"
  keyVaults:
    "reform-scan":
      secrets:
        - name: error-notifications-password
          alias: clients.error-notifications.password
        - name: error-notifications-url
          alias: clients.error-notifications.url
        - name:  error-notifications-username
          alias: clients.error-notifications.username
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

  postgresql:
    enabled: true
    postgresqlUsername: db_user
    postgresqlPassword: db_password
    postgresqlDatabase: db_database
servicebus:
  resourceGroup: reform-scan-aso-preview-rg
  teamName: "BSP"
  location: uksouth
  serviceplan: basic
  sbNamespace: reform-scan
  setup:
    queues:
      - name: notifications
  enabled: true
