base:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  keyVaults:
    tax-tribunals-cft:
      secrets:
        - name: secret-key-base
          alias: SECRET_KEY_BASE
        - name: tt-username
          alias: DB_USERNAME
        - name: tt-password
          alias: DB_PASSWORD
        - name: tt-fqdn
          alias: DB_HOST
        - name: redis-url
          alias: REDIS_URL
        - name: external-url
          alias: EXTERNAL_URL
        - name: tax-tribunals-downloader-url
          alias: TAX_TRIBUNALS_DOWNLOADER_URL
        - name: glimr-api-url
          alias: GLIMR_API_URL
        - name: glimr-direct-api-url-preview
          alias: GLIMR_DIRECT_API_URL
        - name: glimr-direct-enabled
          alias: GLIMR_DIRECT_ENABLED
        - name: upload-problems-report-auth-user
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_USER
        - name: upload-problems-report-auth-digest
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_DIGEST
        - name: admin-username
          alias: ADMIN_USERNAME
        - name: admin-password
          alias: ADMIN_PASSWORD
        - name: sidekiq-admin-password
          alias: SIDEKIQ_ADMIN_PASSWORD
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: report-problem-email-address
          alias: REPORT_PROBLEM_EMAIL_ADDRESS
        - name: tax-tribunal-email
          alias: TAX_TRIBUNAL_EMAIL
        - name: zendesk-username
          alias: ZENDESK_USERNAME
        - name: zendesk-token
          alias: ZENDESK_TOKEN
        - name: sauce-username
          alias: SAUCE_USERNAME
        - name: sauce-access-key
          alias: SAUCE_ACCESS_KEY
        - name: disable-rack-attack-safelists
          alias: DISABLE_RACK_ATTACK_SAFELISTS
        - name: address-lookup-endpoint
          alias: ADDRESS_LOOKUP_ENDPOINT
        - name: address-lookup-api-key
          alias: ADDRESS_LOOKUP_API_KEY
        - name: address-lookup-api-secret
          alias: ADDRESS_LOOKUP_API_SECRET
        - name: maintenance-enabled
          alias: MAINTENANCE_ENABLED
        - name: maintenance-allowed-ips
          alias: MAINTENANCE_ALLOWED_IPS
        - name: azure-storage-account
          alias: AZURE_STORAGE_ACCOUNT
        - name: azure-storage-key
          alias: AZURE_STORAGE_KEY
        - name: azure-storage-container
          alias: AZURE_STORAGE_CONTAINER
        - name: glimr-authorization-key
          alias: GLIMR_AUTHORIZATION_KEY
        - name: glimr-api-client-mock
          alias: GLIMR_API_CLIENT_MOCK
        - name: sentry-dsn-datacapture
          alias: SENTRY_DSN
        - name: tt-storage-account-primary-access-key
          alias: NEW_AZURE_STORAGE_KEY
        - name: dynatrace-ui-tracking-id
          alias: DYNATRACE_UI_TRACKING_ID
        - name: test-loading-env-v1
          alias: TEST_ENV_ID
sidekiq:
  # Don't modify below here
  image: ${IMAGE_NAME}
  keyVaults:
    tax-tribunals-cft:
      secrets:
        - name: secret-key-base
          alias: SECRET_KEY_BASE
        - name: tt-username
          alias: DB_USERNAME
        - name: tt-password
          alias: DB_PASSWORD
        - name: tt-fqdn
          alias: DB_HOST
        - name: redis-url
          alias: REDIS_URL
        - name: external-url
          alias: EXTERNAL_URL
        - name: tax-tribunals-downloader-url
          alias: TAX_TRIBUNALS_DOWNLOADER_URL
        - name: glimr-api-url
          alias: GLIMR_API_URL
        - name: glimr-direct-api-url-preview
          alias: GLIMR_DIRECT_API_URL
        - name: glimr-direct-enabled
          alias: GLIMR_DIRECT_ENABLED
        - name: upload-problems-report-auth-user
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_USER
        - name: upload-problems-report-auth-digest
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_DIGEST
        - name: admin-username
          alias: ADMIN_USERNAME
        - name: admin-password
          alias: ADMIN_PASSWORD
        - name: sidekiq-admin-password
          alias: SIDEKIQ_ADMIN_PASSWORD
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: report-problem-email-address
          alias: REPORT_PROBLEM_EMAIL_ADDRESS
        - name: tax-tribunal-email
          alias: TAX_TRIBUNAL_EMAIL
        - name: zendesk-username
          alias: ZENDESK_USERNAME
        - name: zendesk-token
          alias: ZENDESK_TOKEN
        - name: sauce-username
          alias: SAUCE_USERNAME
        - name: sauce-access-key
          alias: SAUCE_ACCESS_KEY
        - name: disable-rack-attack-safelists
          alias: DISABLE_RACK_ATTACK_SAFELISTS
        - name: address-lookup-endpoint
          alias: ADDRESS_LOOKUP_ENDPOINT
        - name: address-lookup-api-key
          alias: ADDRESS_LOOKUP_API_KEY
        - name: address-lookup-api-secret
          alias: ADDRESS_LOOKUP_API_SECRET
        - name: maintenance-enabled
          alias: MAINTENANCE_ENABLED
        - name: maintenance-allowed-ips
          alias: MAINTENANCE_ALLOWED_IPS
        - name: azure-storage-account
          alias: AZURE_STORAGE_ACCOUNT
        - name: azure-storage-key
          alias: AZURE_STORAGE_KEY
        - name: azure-storage-container
          alias: AZURE_STORAGE_CONTAINER
        - name: glimr-authorization-key
          alias: GLIMR_AUTHORIZATION_KEY
        - name: glimr-api-client-mock
          alias: GLIMR_API_CLIENT_MOCK
        - name: sentry-dsn-datacapture
          alias: SENTRY_DSN
        - name: tt-storage-account-primary-access-key
          alias: NEW_AZURE_STORAGE_KEY
        - name: dynatrace-ui-tracking-id
          alias: DYNATRACE_UI_TRACKING_ID
        - name: test-loading-env-v1
          alias: TEST_ENV_ID
job:
  # Don't modify below here
  image: ${IMAGE_NAME}
  keyVaults:
    tax-tribunals-cft:
      secrets:
        - name: secret-key-base
          alias: SECRET_KEY_BASE
        - name: tt-username
          alias: DB_USERNAME
        - name: tt-password
          alias: DB_PASSWORD
        - name: tt-fqdn
          alias: DB_HOST
        - name: redis-url
          alias: REDIS_URL
        - name: external-url
          alias: EXTERNAL_URL
        - name: tax-tribunals-downloader-url
          alias: TAX_TRIBUNALS_DOWNLOADER_URL
        - name: glimr-api-url
          alias: GLIMR_API_URL
        - name: glimr-direct-api-url-preview
          alias: GLIMR_DIRECT_API_URL
        - name: glimr-direct-enabled
          alias: GLIMR_DIRECT_ENABLED
        - name: upload-problems-report-auth-user
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_USER
        - name: upload-problems-report-auth-digest
          alias: UPLOAD_PROBLEMS_REPORT_AUTH_DIGEST
        - name: admin-username
          alias: ADMIN_USERNAME
        - name: admin-password
          alias: ADMIN_PASSWORD
        - name: sidekiq-admin-password
          alias: SIDEKIQ_ADMIN_PASSWORD
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY
        - name: report-problem-email-address
          alias: REPORT_PROBLEM_EMAIL_ADDRESS
        - name: tax-tribunal-email
          alias: TAX_TRIBUNAL_EMAIL
        - name: zendesk-username
          alias: ZENDESK_USERNAME
        - name: zendesk-token
          alias: ZENDESK_TOKEN
        - name: sauce-username
          alias: SAUCE_USERNAME
        - name: sauce-access-key
          alias: SAUCE_ACCESS_KEY
        - name: disable-rack-attack-safelists
          alias: DISABLE_RACK_ATTACK_SAFELISTS
        - name: address-lookup-endpoint
          alias: ADDRESS_LOOKUP_ENDPOINT
        - name: address-lookup-api-key
          alias: ADDRESS_LOOKUP_API_KEY
        - name: address-lookup-api-secret
          alias: ADDRESS_LOOKUP_API_SECRET
        - name: maintenance-enabled
          alias: MAINTENANCE_ENABLED
        - name: maintenance-allowed-ips
          alias: MAINTENANCE_ALLOWED_IPS
        - name: azure-storage-account
          alias: AZURE_STORAGE_ACCOUNT
        - name: azure-storage-key
          alias: AZURE_STORAGE_KEY
        - name: azure-storage-container
          alias: AZURE_STORAGE_CONTAINER
        - name: glimr-authorization-key
          alias: GLIMR_AUTHORIZATION_KEY
        - name: glimr-api-client-mock
          alias: GLIMR_API_CLIENT_MOCK
        - name: sentry-dsn-datacapture
          alias: SENTRY_DSN
        - name: tt-storage-account-primary-access-key
          alias: NEW_AZURE_STORAGE_KEY
        - name: dynatrace-ui-tracking-id
          alias: DYNATRACE_UI_TRACKING_ID
        - name: test-loading-env-v1
          alias: TEST_ENV_ID
