nodejs:
  applicationPort: 3100
  aadIdentityName: finrem
  ingressHost: finrem-citizen-ui.{{ .Values.global.environment }}.platform.hmcts.net
  image: 'hmctspublic.azurecr.io/finrem/citizen-ui:latest'
  memoryRequests: 1024Mi
  cpuRequests: 2500m
  memoryLimits: 2048Mi
  cpuLimits: 2500m
  readinessDelay: 130
  livenessDelay: 130
  keyVaults:
    finrem:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: idam-secret
          alias: OAUTH2_CLIENT_FINREM
        - name: finrem-idam-client-secret
          alias: FINREM_IDAM_CLIENT_SECRET
  autoscaling:
    enabled: true
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
  environment:
    IDAM_WEB_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token
    IDAM_CLIENT_ID: finrem_citizen_ui
    IDAM_END_SESSION_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o/endSession
    REDIS_EXPIRE_IN_DAYS: 180
    SECURE_COOKIE: 'true'
