# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
java:
  image: https://hmcts.azurecr.io/hmcts/pip-data-management:latest
  ingressHost: 
  devmemoryRequests: 1024Mi
  devmemoryLimits: 2048Mi
  environment:
    ENABLE_TESTING_SUPPORT_API: true
    MANAGED_IDENTITY_CLIENT_ID: 8d0ead51-3b31-44df-a78e-ada4eea9fe87
