# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
job:
  image: https://hmcts.azurecr.io/hmcts/ethos-migration:latest
  ingressHost: 
  kind: CronJob
  schedule: "*/20 * * * *"
  startingDeadlineSeconds: 180
  concurrencyPolicy: Forbid
global:
  jobKind: CronJob
