java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  devApplicationInsightsInstrumentKey: "71df5a0f-ebbe-445c-b1d1-d10d349f0970"
  keyVaults:
    "rpe-send-letter":
      secrets:
        - name: ftp-user
          alias: FTP_USER
        - name: ftp-private-key
          alias: FTP_PRIVATE_KEY
        - name: ftp-public-key
          alias: FTP_PUBLIC_KEY
        - name: xerox-ftp-hostname
          alias: FTP_HOSTNAME
        - name: upload-summary-report-recipients
          alias: UPLOAD_SUMMARY_REPORT_RECIPIENTS
        - name: send-letter-service-staging-db-password
          alias: LETTER_TRACKING_DB_PASSWORD
        - name: send-letter-service-staging-db-user
          alias: LETTER_TRACKING_DB_USER_NAME
        - name: send-letter-service-staging-db-name
          alias: LETTER_TRACKING_DB_NAME
        - name: send-letter-service-staging-db-host
          alias: LETTER_TRACKING_DB_HOST
        - name: send-letter-service-staging-db-port
          alias: LETTER_TRACKING_DB_PORT
        - name: encryption-public-key
          alias: ENCRYPTION_PUBLIC_KEY
        - name: app-insights-instrumentation-key
          alias: azure.application-insights.instrumentation-key
        - name: reports-email-password
          alias: SMTP_PASSWORD
        - name: reports-email-username
          alias: SMTP_USERNAME
        - name: delayed-stale-report-recipients
          alias: DELAYED_STALE_REPORT_RECIPIENTS
        - name: actions-api-key
          alias: ACTIONS_API_KEY

  environment:
    FLYWAY_NOOP_STRATEGY: "false"
