job:
  image: 'hmctspublic.azurecr.io/am/role-assignment-refresh-batch:latest'
  ingressHost: am-role-assignment-refresh-batch-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  applicationPort: 5333
  aadIdentityName: am
  kind: CronJob
  schedule: "*/10 * * * *"
  global:
    jobKind: CronJob
  keyVaults:
    am:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: orm-IDAM-CLIENT-ID
          alias: ORM_IDAM_CLIENT_ID
        - name: orm-IDAM-CLIENT-SECRET
          alias: ORG_ROLE_MAPPING_IDAM_CLIENT_SECRET
        - name: orm-IDAM-ADMIN-SECRET
          alias: ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD
        - name: am-role-assignment-refresh-batch-s2s-secret
          alias: AM_ROLE_ASSIGNMENT_REFRESH_BATCH_SECRET
        - name: role-assignment-service-LD-SDK-KEY
          alias: LD_SDK_KEY
        - name: org-role-mapping-service-POSTGRES-PASS
          alias: ORG_ROLE_MAPPING_DB_PASSWORD
        - name: org-role-mapping-service-POSTGRES-USER
          alias: ORG_ROLE_MAPPING_DB_USERNAME
        - name: org-role-mapping-service-POSTGRES-HOST
          alias: ORG_ROLE_MAPPING_DB_HOST
        - name: role-assignment-refresh-batch-EMAIL-LIST
          alias: EMAIL_LIST
        - name: am-sendgrid-api-key
          alias: AM_SENDGRID_API_KEY
  environment:
    IDAM_S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_USER_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER_URL: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    OPEN_ID_API_BASE_URI: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o
    ORG_ROLE_MAPPING_IDAM_ADMIN_USERID: orm.admin@hmcts.NET
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
    REFRESH_ENV: "{{ .Values.global.environment }}"
    ORG_ROLE_MAPPING_DB_PORT: 5432
    ORG_ROLE_MAPPING_DB_NAME: org_role_mapping
    ORG_ROLE_MAPPING_DB_OPTIONS: "?stringtype=unspecified&sslmode=require"
    AM_ORM_URL: http://am-org-role-mapping-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AM_RAS_URL: http://am-role-assignment-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    EMAIL_ENABLED: false


