java:
    applicationPort: 4012
    aadIdentityName: nfdiv
    ingressHost: "nfdiv-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    environment:
        CASE_MAINTENANCE_SERVICE_API_BASEURL: "http://nfdiv-cms-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        PAYMENT_API_BASEURL: "http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        PRD_API_BASEURL : "http://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
        IDAM_API_REDIRECT_URL: "https://div-pfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/authenticated"
        SERVICE_AUTH_PROVIDER_URL: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        CASE_VALIDATION_SERVICE_API_BASEURL: "http://div-vs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DOCUMENT_GENERATOR_SERVICE_API_BASEURL: "http://div-dgs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        FEES_AND_PAYMENTS_SERVICE_API_BASEURL: "http://div-fps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        ACA_SERVICE_API_BASEURL: "http://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        CCD_DATA_STORE_API_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
        MANAGEMENT_ENDPOINT_HEALTH_CACHE_TIMETOLIVE: "30000"
        SCHEDULER_RE_CREATE: true
        FEATURE_DN_REFUSAL: "true"
        FEATURE_RESP_SOLICITOR_DETAILS: true
        DIV_SCHEDULER_DB_HOST : "nfdiv-cos-{{ .Values.global.environment }}.postgres.database.azure.com"
        DIV_SCHEDULER_DB_PORT : "5432"
        DIV_SCHEDULER_DB_NAME : "div_scheduler"
        DIV_SCHEDULER_DB_USER_NAME : "div_scheduler@nfdiv-cos-{{ .Values.global.environment }}"
        FLYWAY_URL : "jdbc:postgresql://nfdiv-cos-{{ .Values.global.environment }}.postgres.database.azure.com:5432/div_scheduler"
        SPRING_MAIL_HOST: mta.reform.hmcts.net
        SPRING_MAIL_PORT: 25
        SPRING_MAIL_TEST_CONNECTION: false
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: true
        SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mta.reform.hmcts.net
    keyVaults:
        "nfdiv":
            resourceGroup: nfdiv
            secrets:
                - AppInsightsInstrumentationKey
                - cms-service-key
                - div-doc-s2s-auth-secret
                - idam-secret
                - cos-service-key
                - idam-citizen-username
                - idam-citizen-password
                - idam-caseworker-username
                - idam-caseworker-password
                - uk-gov-notify-api-key
                - cos-postgresql-password
