java:
  applicationPort: 8080
  image: 'hmctspublic.azurecr.io/ccpay/notifications-service:latest'
  ingressHost: ccpay-notifications-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  environment:
    POSTGRES_PORT: 5432
    POSTGRES_NAME: notifications
    POSTGRES_CONNECTION_OPTIONS: ?sslmode=require
    SPRING_LIQUIBASE_ENABLED: true
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    AUTH_IDAM_CLIENT_BASEURL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    ISSUER_URI: "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/o"
    OIDC_CLIENT_ID: "paybubble"
    OIDC_ISSUER: "https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts"
    OIDC_S2S_MICROSERVICE_NAME: notifications_service
    OIDC_AUDIENCE_LIST: refunds_api,cmc_citizen,ccd_gateway,xuiwebapp,xuimowebapp,xuiaowebapp
    S2S_AUTHORISED_SERVICES: refunds_api,ccpay_bubble,api_gw,ccd_gw,xui_webapp,payment_app
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    LAUNCH_DARKLY_USER_NAME_PREFIX: '{{ .Values.global.environment }}'
    PAYMENT_API_URL: "http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  keyVaults:
    "ccpay":
      resourceGroup: ccpay
      secrets:
        - name: notifications-service-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
        - name: notifications-service-POSTGRES-USER
          alias: POSTGRES_USERNAME
        - name: notifications-service-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: notifications-s2s-secret
          alias: OIDC_S2S_SECRET
        - name: notifications-email-apikey
          alias: EMAIL_APIKEY
        - name: notifications-letter-apikey
          alias: LETTER_APIKEY
        - name: freg-idam-generated-user-email-pattern
          alias: GENERATED_USER_EMAIL_PATTERN
        - name: refunds-api-user-password
          alias: REFUND_SERVICE_ACCOUNT_PASSWORD
        - name: refunds-api-client-secret
          alias: REFUND_SERVICE_ACCOUNT_CLIENT_SECRET
        - name: notifications-letter-template-id
          alias: NOTIFICATION_LETTER_TEMPLATE_ID
        - name: notifications-email-template-id
          alias: NOTIFICATION_EMAIL_TEMPLATE_ID
        - name: notifications-letter-cheque-po-cash-template-id
          alias: NOTIFICATIONS_LETTER_CHEQUE_PO_CASH_TEMPLATE_ID
        - name: notifications-email-cheque-po-cash-template-id
          alias: NOTIFICATIONS_EMAIL_CHEQUE_PO_CASH_TEMPLATE_ID
        - name: notifications-letter-card-pba-template-id
          alias: NOTIFICATION_LETTER_CARD_PBA_TEMPLATE_ID
        - name: notifications-email-card-pba-template-id
          alias: NOTIFICATION_EMAIL_CARD_PBA_TEMPLATE_ID
        - name: notifications-letter-refund-when-contacted-template-id
          alias: NOTIFICATION_LETTER_REFUND_WHEN_CONTACTED_TEMPLATE_ID
        - name: notifications-email-refund-when-contacted-template-id
          alias: NOTIFICATION_EMAIL_REFUND_WHEN_CONTACTED_TEMPLATE_ID
        - name: postcode-address-lookup-id
          alias: POSTCODE_ADDRESS_LOOKUP_ID
        - name: app-insights-connection-string
          alias: app-insights-connection-string
