tags:
  ccd-idam-pr: false

ccd:
  postgres:
    enabled: false
  elastic:
    enabled: false
  xui:
    enabled: false

xui-webapp:
  enabled: false

xui-mo-webapp:
  enabled: false

aac-manage-case-assignment:
  enabled: false

idam-pr:
  enabled: false

ccd-case-document-am-api:
  enabled: false

em-ccdorc:
  enabled: false

em-stitching:
  enabled: false

wa:
  enabled: false
am-org-role-mapping-service:
  enabled: false
servicebus:
  enabled: false

java:
  applicationPort: 4013
  image: 'hmctspublic.azurecr.io/sptribs/case-api:latest'
  ingressHost: sptribs-case-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  spotInstances:
    enabled: true
  aadIdentityName: sptribs
  keyVaults:
    sptribs:
      secrets:
        - name: app-insights-instrumentation-key
        - name: app-insights-connection-string
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY_1
        - name: s2s-case-api-secret
          alias: S2S_SECRET
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: launchdarkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
        - name: idam-systemupdate-username
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-systemupdate-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: ccd-case-events-sendonly-connection-string
          alias: AZURE_SERVICE_BUS_CONNECTION_STRING
        - name: sptribs-POSTGRES-HOST
          alias: POSTGRES_HOST
        - name: sptribs-POSTGRES-PORT
          alias: POSTGRES_PORT
        - name: sptribs-POSTGRES-DATABASE
          alias: POSTGRES_NAME
        - name: sptribs-POSTGRES-USER
          alias: POSTGRES_USERNAME
        - name: sptribs-POSTGRES-PASS
          alias: POSTGRES_PASSWORD
  environment:
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    FEE_API_URL: http://fees-register-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    LOCATION_API_URL: http://rd-location-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    REF_DATA_COMMON_API_URL: http://rd-commondata-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    JUDICIAL_API_URL: http://rd-judicial-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    BUNDLING_API_URL: http://em-ccd-orchestrator-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    IDAM_API_REDIRECT_URL: https://div-pfe-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/authenticated
    IDAM_API_BASEURL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    CASE_DATA_STORE_BASEURL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CASE_DOCUMENT_AM_BASEURL: http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOC_ASSEMBLY_URL: http://dg-docassembly-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    DOCUMENT_MANAGEMENT_URL: http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal

    CASE_API_DOCUMENT_DOWNLOAD_URL: http://manage-case.{{ .Values.global.environment }}.platform.hmcts.net/
    SEND_LETTER_SERVICE_BASEURL: "http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    SERVICE_AUTH_MICROSERVICE: sptribs_case_api
    SERVICE_AUTH_PROVIDER_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    NOTIFY_TEMPLATE_SIGN_IN_PROFESSIONAL_USERS_URL: https://manage-case.{{ .Values.global.environment }}.platform.hmcts.net/cases/case-details/
    S2S_AUTHORISED_SERVICES: ccd_definition,ccd_data,xui_webapp,sptribs_case_api,ccd_gw,sptribs_frontend,sptribs_dss_update_case_web

