java:
  image: https://hmcts.azurecr.io/hmcts/sptribs-case-api:latest
  ingressHost: 
  keyVaults:
    sptribs:
      secrets:
        - name: app-insights-instrumentation-key
        - name: app-insights-connection-string
        - name: uk-gov-notify-api-key
          alias: UK_GOV_NOTIFY_API_KEY_1
        - name: s2s-case-api-secret
          alias: S2S_SECRET
        - name: idam-secret
          alias: IDAM_CLIENT_SECRET
        - name: idam-systemupdate-username
          alias: IDAM_SYSTEM_UPDATE_USERNAME
        - name: idam-systemupdate-password
          alias: IDAM_SYSTEM_UPDATE_PASSWORD
        - name: launchdarkly-sdk-key
          alias: LAUNCH_DARKLY_SDK_KEY
