# Don't modify this file, it is only needed for the pipeline to set the image and ingressHost
nodejs:
  image: https://hmcts.azurecr.io/hmcts/darts-portal:latest
  ingressHost: 
  environment:
    DARTS_API_URL: https://darts-api.staging.platform.hmcts.net
    DARTS_PORTAL_URL: https://darts-portal.staging.platform.hmcts.net
