nodejs:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/juror-er-portal:latest
  ingressHost: 
  environment:
    API_ENDPOINT: https://juror-api.staging.platform.hmcts.net/api/v1
    REDIRECT_URI: https://juror-er.staging.apps.hmcts.net/auth/redirect
    POST_LOGOUT_REDIRECT_URI: https://juror-er.staging.apps.hmcts.net
    SKIP_SSO: true
