nodejs:
  image: 'sdshmctspublic.azurecr.io/juror/er-portal:latest'
  applicationPort: 3000
  ingressHost: juror-er-portal.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: juror
  keyVaults:
    juror:
      secrets:
        - name: er-portal-sessionSecret
        - name: er-portal-jwtKey
        - name: er-portal-jwtNoAuthKey
        - name: er-portal-jwtTTL
        - name: app-insights-connection-string
        - name: er-portal-redisConnection
  environment:
    API_ENDPOINT: https://juror-api.{{ .Values.global.environment }}.platform.hmcts.net/api/v1
    ALLOW_CONFIG_MUTATIONS: true
