nodejs:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    API_ENDPOINT: https://juror-api.staging.platform.hmcts.net/api/v1
    REDIRECT_URI: https://${SERVICE_FQDN}/auth/redirect
    POST_LOGOUT_REDIRECT_URI: https://${SERVICE_FQDN}
    SKIP_SSO: true
