java:
  applicationPort: 8090
  image: 'hmctspublic.azurecr.io/fis/bulk-scan-api:latest'
  ingressHost: fis-bulk-scan-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: fis

  environment:
    NODE_ENV: production
    REFORM_TEAM: fis
    REFORM_SERVICE_NAME: fis-bulk-scan-api

    SERVICE_AUTH_PROVIDER_URL: 'http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal'
    IDAM_WEB_URL: 'https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login'
    IDAM_API_URL: 'https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net/o/token'


  keyVaults:
    fis:
      secrets:
        - idam-ui-secret
        - idam-system-user-name
        - idam-system-user-password
        - s2s-secret
        - AppInsightsInstrumentationKey
        - postcode-lookup-token

