---
java:
  image: 'sdshmctspublic.azurecr.io/vh/test-api:latest'
  applicationPort: 8080
  replicas: 2
  ingressHost: vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net
  releaseNameOverride: vh-test-api
  readinessPath: /healthcheck/health
  livenessPath: /healthcheck/health
  livenessDelay: 360
  livenessPeriod: 120
  aadIdentityName: vh-aad-identity
  keyVaults:
    vh-infra-core:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - connectionstrings--testapi
        - applicationinsights--instrumentationkey
    vh-test-api:
      excludeEnvironmentSuffix: false
      resourceGroup: vh-infra-core-{{ .Values.global.environment }}
      usePodIdentity: true
      secrets:
        - azuread--clientsecret
        - azuread--clientid
  environment:
    ASPNETCORE_URLS: http://+:8080
    AZUREAD__TENANTID: "fb6e0e22-0da3-4c35-972a-9d61eb256508"
    DISABLEHTTPSREDIRECTION: true
    SERVICES__TESTAPIRESOURCEID: https:/vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES__BOOKINGSAPIRESOURCEID: https://vh-bookings-api.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES__USERAPIRESOURCEID: https://vh-user-api.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES__VIDEOAPIRESOURCEID: https://vh-video-api.{{ .Values.global.environment }}.platform.hmcts.net
    SERVICES__TESTAPIURL: https://vh-test-api.{{ .Values.global.environment }}.platform.hmcts.net/
    SERVICES__BOOKINGSAPIURL: https://vh-bookings-api.{{ .Values.global.environment }}.platform.hmcts.net/
    SERVICES__USERAPIURL: https://vh-user-api.{{ .Values.global.environment }}.platform.hmcts.net/
    SERVICES__VIDEOAPIURL: https://vh-video-api.{{ .Values.global.environment }}.platform.hmcts.net/
    TESTING__TESTUSERNAMESTEM: "@hearings.reform.hmcts.net"
    Logging__LogLevel__Default: debug
    Logging__LogLevel__System: debug
    Logging__LogLevel__Microsoft: debug