java:
  applicationPort: 8080
  image: 'sdshmctspublic.azurecr.io/juror/pnc:latest'
  ingressHost: juror-scheduler-execution.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: juror
  keyVaults:
    juror:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: api-POSTGRES-CONNECTION-STRING
          alias: DB_URL
        - name: api-POSTGRES-USER
          alias: DB_USERNAME
        - name: api-POSTGRES-PASS
          alias: DB_PASSWORD
        - name: scheduler-execution-SECRET
          alias: SECRET
        - name: scheduler-api-SECRET
          alias: SCHEDULER_SERVICE_SECRET
        - name: pnc-SECRET
          alias: POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_SECRET
        - name: api-JWT-SECRET-BUREAU
          alias: JUROR_SERVICE_SECRET
        - name: bais-host
          alias: BAIS_HOST
        - name: bais-xerox-user
          alias: BAIS_XEROX_USER
        - name: bais-xerox-key
        - name: bais-sscl-user
          alias: BAIS_SSCL_USER
        - name: bais-sscl-key
  environment:
    SCHEDULER_SERVICE_HOST: juror-scheduler-api.{{ .Values.global.environment }}.platform.hmcts.net
    SCHEDULER_SERVICE_PORT: 443
    SCHEDULER_SERVICE_SUBJECT: external-api@juror-scheduler-api.hmcts.net
    POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_HOST: juror-pnc.{{ .Values.global.environment }}.platform.hmcts.net
    POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_PORT: 443
    POLICE_NATIONAL_COMPUTER_CHECK_SERVICE_SUBJECT: api.job.execution.service@schedular.cgi.com
    JUROR_SERVICE_HOST: juror-api.{{ .Values.global.environment }}.platform.hmcts.net
    JUROR_SERVICE_PORT: 443
    BAIS_PORT: 22
    SPRING_PROFILES_ACTIVE: test
