java:
  applicationPort: 8095
  image: 'hmctspublic.azurecr.io/rd/caseworker-ref-api:latest'
  ingressHost: rd-caseworker-ref-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  environment:
    POSTGRES_HOST: rd-caseworker-ref-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: dbrdcaseworker@rd-caseworker-ref-api-postgres-db-{{ .Values.global.environment }}
    POSTGRES_DB_NAME: dbrdcaseworker
    POSTGRES_PORT: 5432
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    CWRD_MQ_HOST: rd-servicebus-{{ .Values.global.environment }}.servicebus.windows.net
    CWRD_MQ_USERNAME: SendAndListenSharedAccessKey
    CWRD_MQ_TOPIC_NAME: rd-caseworker-topic-{{ .Values.global.environment }}
    CWRD_MQ_TRUST_ALL_CERTS: false
    CWRD_DATA_PER_MESSAGE: 50
    LAUNCH_DARKLY_ENV: "{{ .Values.global.environment }}"
  keyVaults:
    rd:
      secrets:
        - caseworker-ref-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
        - caseworker-topic-primary-send-listen-shared-access-key
        - caseworker-ref-api-s2s-secret
        - LD-SDK-KEY