base:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/et-pet-et1:latest
  ingressHost: 
  devmemoryLimits: "3Gi"
  devmemoryRequests: "768Mi"
  devcpuLimits: "500m"
  devcpuRequests: "250m"
  environment:
    DYNATRACE_UI_TRACKING_ID: "bf24054dsx/4bf1f9dd4856af92"
