java:
  applicationPort: 4065
  image: 'hmctspublic.azurecr.io/opal/logging-service:latest'
  ingressHost: opal-logging-service-{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: opal
  keyVaults:
    opal:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: logging-service-POSTGRES-HOST
          alias: OPAL_LOGGING_DB_HOST
        - name: logging-service-POSTGRES-PASS
          alias: OPAL_LOGGING_DB_PASSWORD
        - name: logging-service-POSTGRES-PORT
          alias: OPAL_LOGGING_DB_PORT
        - name: logging-service-POSTGRES-USER
          alias: OPAL_LOGGING_DB_USERNAME
        - name: logging-service-POSTGRES-DATABASE
          alias: OPAL_LOGGING_DB_NAME
        - name: servicebus-connection-string
          alias: SERVICEBUS_CONNECTION_STRING
        - name: servicebus-shared-access-key
          alias: SERVICEBUS_SHARED_ACCESS_KEY
        - name: servicebus-logging-pdpl-queue-name
          alias: SERVICEBUS_LOGGING_PDPL_QUEUE_NAME
servicebus:
  enabled: false