function:
  image: hmctspublic.azurecr.io/ccpay/payment-status-callback-function
  trigger:
    type: azure-servicebus
    servicebus:
      topicName: "ccpay-payment-status-update-topic"
      subscriptionName: defaultServiceCallbackSubscription
      connection: SERVICE_CALLBACK_BUS_CONNECTION
      queueLength: 1
  aadIdentityName: ccpay
  keyVaults:
    "ccpay":
      secrets:
        - payment-s2s-secret
  environment:
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    MICROSERVICE_PAYMENT_APP: "payment_app"
servicebus:
  enabled: false