job:
  applicationPort: 8099
  image: 'hmctspublic.azurecr.io/rd/location-ref-data-load:latest'
  ingressHost: rd-location-ref-data-load-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: rd
  environment:
    POSTGRES_HOST: rd-location-ref-api-postgres-db-{{ .Values.global.environment }}.postgres.database.azure.com
    POSTGRES_USERNAME: dbrdlocationref@rd-location-ref-api-postgres-db-{{ .Values.global.environment }}
    POSTGRES_NAME: dbrdlocationref
    POSTGRES_PORT: 5432
    LOGBACK_REQUIRE_ALERT_LEVEL: 'false'
    LOGBACK_REQUIRE_ERROR_CODE: 'false'
    FLYWAY_ENABLED: false
    postgresql:
      enabled: false
    image: 'hmctspublic.azurecr.io/rd/location-ref-data-load:latest'

  keyVaults:
    "rd":
      resourceGroup: rd
      secrets:
        - location-ref-api-POSTGRES-PASS
        - AppInsightsInstrumentationKey
        - LRD-ACCOUNT-NAME
        - LRD-ACCOUNT-KEY
        - CONTAINER-NAME
        - BLOB-URL-SUFFIX
  postgresql:
    enabled: false

  blobstorage:
    enabled: false

  global:
    jobKind: CronJob
