java:
  # Don't modify below here
  image: https://hmcts.azurecr.io/hmcts/em-anno:latest
  ingressHost: 
  environment:
    DELETE_DOCUMENT_DATA_WHITELIST: dm_store,em_gw
    ENABLE_DOCUMENT_DELETE_ENDPOINT: true
